// <auto-generated />
using System;
using MVCCoreNet.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCCoreNet.Migrations
{
    [DbContext(typeof(MVCContext))]
    [Migration("20181102225254_MIG_ModificationLibEtCategorie")]
    partial class MIG_ModificationLibEtCategorie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCCoreNet.Models.Categorie", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom");

                    b.Property<bool>("Tag");

                    b.HasKey("IdCategorie");

                    b.ToTable("Categorie");
                });

            modelBuilder.Entity("MVCCoreNet.Models.Hebergement", b =>
                {
                    b.Property<int>("IdHebergement")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdLib");

                    b.Property<string>("Intitule");

                    b.Property<string>("Url");

                    b.HasKey("IdHebergement");

                    b.ToTable("Hebergement");
                });

            modelBuilder.Entity("MVCCoreNet.Models.Lib", b =>
                {
                    b.Property<int>("IdLib")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("IdCategorie");

                    b.Property<string>("Information");

                    b.Property<string>("Nom");

                    b.HasKey("IdLib");

                    b.HasIndex("IdCategorie");

                    b.ToTable("Lib");
                });

            modelBuilder.Entity("MVCCoreNet.Models.Lien", b =>
                {
                    b.Property<int>("IdLien")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdLib");

                    b.Property<string>("Intitule");

                    b.Property<string>("Url");

                    b.HasKey("IdLien");

                    b.HasIndex("IdLib");

                    b.ToTable("Lien");
                });

            modelBuilder.Entity("MVCCoreNet.Models.Lib", b =>
                {
                    b.HasOne("MVCCoreNet.Models.Categorie", "Categorie")
                        .WithMany("Etudiants")
                        .HasForeignKey("IdCategorie");
                });

            modelBuilder.Entity("MVCCoreNet.Models.Lien", b =>
                {
                    b.HasOne("MVCCoreNet.Models.Lib")
                        .WithMany("Lien")
                        .HasForeignKey("IdLib")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
